server:
  port: 8090
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mt_core_transfers
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    producer:
      properties:
        allow.auto.create.topics: true
        spring:
          json:
            add:
              type:
                headers: false
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    consumer:
      properties:
        allow.auto.create.topics: true
        enable.auto.commit: false
        spring:
          json:
            value:
              default:
                type: ru.otus.java.pro.mt.core.transfers.entities.Transfer
      bootstrap-servers: localhost:9092
      group-id: local.otus.transfers.group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
topic:
  transfers: local.otus.transfers

transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
integrations:
  limits:
    url: http://localhost:8080/api/v1/limits
    read-timeout: 30s
    write-timeout: 2s
